[package]
authors = ["Andreas Linz <klingt.net@gmail.com>"]
description = "An OSC library for Rust"
documentation = "https://docs.rs/rosc"
keywords = ["audio", "osc"]
license = "MIT/Apache-2.0"
name = "rosc"
readme = "README.md"
repository = "https://github.com/klingtnet/rosc"
rust-version = "1.52"
version = "0.10.1"

[features]
default = ["std"]
lints = ["clippy"]
std = []

[dependencies]
byteorder = {version = "1", default-features = false}
clippy = {version = "^0", optional = true}
nom = {version = "7", default-features = false, features = ["alloc"]}
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
hex = {version = "0.4"}
